### ISSUE TITLE
Does not find the Wi-Fi network

### ISSUE THREAD

**Issue by Charus-OV** [makerbase-mks/MKS-DLC32#306]
With the latest firmware [V2.20_H35_2022_1101_N_ZX_002.bin](https://github.com/makerbase-mks/MKS-DLC32/blob/main/firmware/TS35/Laser/Normal/Board_V2.0/V2.20_H35_2022_1101_N_ZX_002.bin), it cannot find the Wi-Fi network in dynamic mode

**Comment by pekkaojanpera** [comment]
Yes, I can confirm that. No wifi network found.

**Comment by tosad11665** [comment]
Me to. They never find any Wify Network!

**Comment by silvanopas** [comment]
I confirm, it does not find any SSID

**Comment by abinoer** [comment]
Fixed, please update firmware

**Comment by AlesH79** [comment]
Please can you update also the CNC firmware, this one is old at list 7mounts.
Tnx

**Comment by AlesH79** [comment]
There is also an issue. I can modify the radio/mode, switch the $radio/mode=AP to $radio/mode=STA it is working, but if I press $I to check the actual set-up there is still shown AP mode.
can you check?
